/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    // "aws_project_region": "ap-south-1",
    // "aws_cognito_identity_pool_id": "ap-south-1:cfc362d7-915e-4466-b869-f0a5aeebaf46",
    // "aws_cognito_region": "ap-south-1",
    // "aws_user_pools_id": "ap-south-1_uXfb5L07a",
    // "aws_user_pools_web_client_id": "5bqul9tohehve6looeq61pmt27",
    // "oauth": {},

    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:cfc362d7-915e-4466-b869-f0a5aeebaf46",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_uXfb5L07a",
    "aws_user_pools_web_client_id": "5bqul9tohehve6looeq61pmt27",
    "oauth": {},

    "aws_appsync_graphqlEndpoint": "https://e7uvuythtfaohhdd67pe6vev2i.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-owqep2s2bjbsldj455z4eowkmy",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true
};


export default awsmobile;
